#
# Copyright (c) 2020-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Release Che Plugin Registry

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release version in format 7.y.z'
        required: true
      forceRecreateTags:
        description: If true, tags will be recreated. Use with caution
        required: false
        default: 'false'

jobs:
  release-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to Quay.io
        uses: azure/docker-login@v1
        with:
          login-server: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Login to Docker Hub
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        name: Cache yarn dependencies
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/cache@v2
        name: Cache vsix dependencies
        id: download-unpacked-cache
        with:
          path: | 
            /tmp/che-plugin-registry/download-folder
            /tmp/che-plugin-registry/unpack-folder
          key: download-unpacked-cache-${{ hashFiles('**/che-theia-plugins.yaml') }}
          restore-keys: |
            download-unpacked-cache-
      - name: Extract content for publishing
        run: |
          docker pull quay.io/eclipse/che-plugin-registry:${{ github.event.inputs.version}}
          docker create --name pluginRegistry quay.io/eclipse/che-plugin-registry:${{ github.event.inputs.version}} sh
          mkdir content
          docker cp pluginRegistry:/var/www/html/v3 content/v3
          docker rm -f pluginRegistry
          cp content/v3/plugins/index.json content/index.json
      - name: publish to npmjs
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd tools/build
          npm publish --tag latest
