#
# Copyright (c) 2020-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Resource Limits PR Check

on:
  pull_request:
    branches: 
      - main
    paths:
      - 'che-theia-plugins.yaml'

jobs:
  executable-permissions-pr-check:
    runs-on: ubuntu-20.04

    steps:
    - name: Clone source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Test command
      run: |
        ls -la ./
